version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/docker-compose"
    schedule:
      interval: "weekly"

  # Docker (Dockerfile for the Blazor App)
  - package-ecosystem: "docker"
    directory: "/src/Viagem"
    schedule:
      interval: "weekly"

  # NuGet (Main App)
  - package-ecosystem: "nuget"
    directory: "/src/Viagem"
    schedule:
      interval: "weekly"

  # NuGet (Data Library)
  - package-ecosystem: "nuget"
    directory: "/src/Viagem.Data"
    schedule:
      interval: "weekly"

  # NuGet (Tests)
  - package-ecosystem: "nuget"
    directory: "/src/Viagem.UnitTests"
    schedule:
      interval: "weekly"
