// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viagem.Data;

#nullable disable

namespace Viagem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Viagem.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapsProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Viagem.Data.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Viagem.Data.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcaoCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsoCountry")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Municipality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IataCode");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Viagem.Data.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Viagem.Data.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Viagem.Data.Models.SiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerAdditionalField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TravellerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TravellerProfileId");

                    b.ToTable("TravellerAdditionalFields");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravellerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TravellerProfileId");

                    b.ToTable("TravellerAttachments");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("OwnerId");

                    b.ToTable("TravellerProfiles");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfileAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TravellerProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TravellerProfileId");

                    b.ToTable("TravellerProfileAliases");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfileManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TravellerProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("TravellerProfileId");

                    b.ToTable("TravellerProfileManagers");
                });

            modelBuilder.Entity("Viagem.Data.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BudgetCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Viagem.Data.Models.TripTraveller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrganiser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravellerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TravellerProfileId");

                    b.HasIndex("TripId");

                    b.ToTable("TripTravellers");
                });

            modelBuilder.Entity("Viagem.Data.Models.UserTravelDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId", "PlaceId");

                    b.ToTable("UserTravelDestinations");
                });

            modelBuilder.Entity("Viagem.Data.Models.UserTravelStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActivityAvgPerTrip")
                        .HasColumnType("REAL");

                    b.Property<int>("ActivityTotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseCurrencyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpenseStatsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LodgingStatsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LodgingTotalNights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TransportationAvgHours")
                        .HasColumnType("REAL");

                    b.Property<string>("TransportationStatsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TransportationTotalHours")
                        .HasColumnType("REAL");

                    b.Property<int>("TransportationTotalTrips")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year")
                        .IsUnique();

                    b.ToTable("UserTravelStats");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viagem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viagem.Data.Models.Notification", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerAdditionalField", b =>
                {
                    b.HasOne("Viagem.Data.Models.TravellerProfile", "TravellerProfile")
                        .WithMany("AdditionalFields")
                        .HasForeignKey("TravellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravellerProfile");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerAttachment", b =>
                {
                    b.HasOne("Viagem.Data.Models.TravellerProfile", "TravellerProfile")
                        .WithMany("Attachments")
                        .HasForeignKey("TravellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravellerProfile");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfile", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Viagem.Data.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LinkedUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfileAlias", b =>
                {
                    b.HasOne("Viagem.Data.Models.TravellerProfile", "TravellerProfile")
                        .WithMany("Aliases")
                        .HasForeignKey("TravellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravellerProfile");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfileManager", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viagem.Data.Models.TravellerProfile", "TravellerProfile")
                        .WithMany("Managers")
                        .HasForeignKey("TravellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerUser");

                    b.Navigation("TravellerProfile");
                });

            modelBuilder.Entity("Viagem.Data.Models.Trip", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Viagem.Data.Models.Activity", "Activities", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Address");

                            b1.PrimitiveCollection<string>("AttachmentIds")
                                .IsRequired();

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<string>("Description");

                            b1.Property<DateTime?>("EndDate");

                            b1.Property<Guid?>("ExpenseId");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Link");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Notes");

                            b1.Property<int?>("PlaceId");

                            b1.Property<DateTime>("StartDate");

                            b1.Property<string>("Timezone");

                            b1.PrimitiveCollection<string>("TravellerProfileIds")
                                .IsRequired();

                            b1.Property<DateTime>("UpdatedAt");

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("Activities")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsMany("Viagem.Data.Models.Expense", "Expenses", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<decimal?>("Amount");

                            b1.PrimitiveCollection<string>("AttachmentIds")
                                .IsRequired();

                            b1.Property<int?>("Category");

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<string>("CreatedById");

                            b1.Property<string>("Currency");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Notes");

                            b1.Property<DateTime?>("OccurredOn");

                            b1.Property<Guid?>("SourceId");

                            b1.Property<string>("SourceType");

                            b1.Property<DateTime>("UpdatedAt");

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("Expenses")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TripId");

                            b1.OwnsMany("Viagem.Data.Models.ExpenseSplit", "Splits", b2 =>
                                {
                                    b2.Property<int>("ExpenseTripId");

                                    b2.Property<int>("Expense__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<decimal>("Amount");

                                    b2.Property<int>("TravellerProfileId");

                                    b2.HasKey("ExpenseTripId", "Expense__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Trips");

                                    b2.WithOwner()
                                        .HasForeignKey("ExpenseTripId", "Expense__synthesizedOrdinal");
                                });

                            b1.Navigation("Splits");
                        });

                    b.OwnsMany("Viagem.Data.Models.Lodging", "Lodgings", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Address");

                            b1.PrimitiveCollection<string>("AttachmentIds")
                                .IsRequired();

                            b1.Property<string>("ConfirmationCode");

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<DateTime>("EndDate");

                            b1.Property<Guid?>("ExpenseId");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Link");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Notes");

                            b1.Property<int?>("PlaceId");

                            b1.Property<DateTime>("StartDate");

                            b1.Property<string>("Timezone");

                            b1.PrimitiveCollection<string>("TravellerProfileIds")
                                .IsRequired();

                            b1.Property<int>("Type");

                            b1.Property<DateTime>("UpdatedAt");

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("Lodgings")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsMany("Viagem.Data.Models.Transportation", "Transportations", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateTime>("ArrivalTime");

                            b1.Property<string>("ArrivalTimezone");

                            b1.Property<string>("AssignedSeats");

                            b1.PrimitiveCollection<string>("AttachmentIds")
                                .IsRequired();

                            b1.Property<string>("ConfirmationCode");

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<DateTime>("DepartureTime");

                            b1.Property<string>("DepartureTimezone");

                            b1.Property<string>("Destination");

                            b1.Property<string>("DestinationCity");

                            b1.Property<int?>("DestinationPlaceId");

                            b1.Property<string>("DropOffLocation");

                            b1.Property<Guid?>("ExpenseId");

                            b1.Property<string>("FlightNumber");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Link");

                            b1.Property<string>("Notes");

                            b1.Property<string>("Origin");

                            b1.Property<string>("OriginCity");

                            b1.Property<int?>("OriginPlaceId");

                            b1.Property<string>("ParkingAddress");

                            b1.Property<string>("PickupLocation");

                            b1.Property<string>("Provider");

                            b1.Property<string>("RentalCompany");

                            b1.Property<string>("SpotNumber");

                            b1.PrimitiveCollection<string>("TravellerProfileIds")
                                .IsRequired();

                            b1.Property<int>("Type");

                            b1.Property<DateTime>("UpdatedAt");

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("Transportations")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsMany("Viagem.Data.Models.TripAttachment", "Attachments", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("ContentType");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<string>("FilePath")
                                .IsRequired();

                            b1.Property<long>("FileSize");

                            b1.Property<Guid>("Id");

                            b1.Property<DateTime>("UploadedAt");

                            b1.Property<string>("UploadedById")
                                .IsRequired();

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("Attachments")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsMany("Viagem.Data.Models.TripDestination", "Destinations", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("CustomName");

                            b1.Property<Guid>("Id");

                            b1.Property<int?>("PlaceId");

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("Destinations")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Attachments");

                    b.Navigation("Destinations");

                    b.Navigation("Expenses");

                    b.Navigation("Lodgings");

                    b.Navigation("Owner");

                    b.Navigation("Transportations");
                });

            modelBuilder.Entity("Viagem.Data.Models.TripTraveller", b =>
                {
                    b.HasOne("Viagem.Data.Models.TravellerProfile", "TravellerProfile")
                        .WithMany()
                        .HasForeignKey("TravellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viagem.Data.Models.Trip", "Trip")
                        .WithMany("Travellers")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravellerProfile");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Viagem.Data.Models.UserTravelDestination", b =>
                {
                    b.HasOne("Viagem.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Viagem.Data.Models.UserTravelStats", b =>
                {
                    b.HasOne("Viagem.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viagem.Data.Models.TravellerProfile", b =>
                {
                    b.Navigation("AdditionalFields");

                    b.Navigation("Aliases");

                    b.Navigation("Attachments");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("Viagem.Data.Models.Trip", b =>
                {
                    b.Navigation("Travellers");
                });
#pragma warning restore 612, 618
        }
    }
}
